### ISSUE TITLE
Document the JSON API

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#387]
This is a journey issue to compile related issues for API documentation.

We should document our JSON API using:
- [API Blueprint](https://apiblueprint.org/) for writing the documentation of resources, actions, and URIs
- [Apiary](https://apiary.io/) for browsing the docs

Aiming to keep PRs ~200 LOC where possible.

For each of the Issues below, please order the CRUD functions as so:

```
Create
Retrieve
Update
Delete
List (Retrieve Index)
```

The location for the API documentation is under `blueprint/api.apib`

Priority for remaining endpoints:
### In progress
- [ ] Document Ping API #411 _in progress_
- [ ] Document Posts API #415 _in progress_
### Low priority

These can be done after the Phoenix migration and are not critical for its first release. Listed in order of priority.
- [ ] Document Post User Mentions API #414
- [ ] Document Preview User Mentions API #416
- [ ] Document Project Roles API #419
- [ ] Document Github Repositories API #405
- [ ] Document Post Images API #412
- [ ] Document Post Likes API #413
### Different implementation

These endpoints may need a different implementation in Phoenix than in Rails, so we should reconsider whether to document them.
- [ ] Document Ember Index API #404
- [ ] Document Import Skill Failures API #406
- [ ] Document Imports API #407
- [ ] Document OAuth Applications API #408
### Already finished
- [x] Document Categories API #400
- [x] Document Comment Images API #401
- [x] Document Comment User Mentions API #402 _in progress_
- [x] Document Comments API #403 _in progress_
- [x] Document Organization Memberships API #409
- [x] Document Organizations API #410
- [x] Document Previews API #417
- [x] Document Project Categories API #418
- [x] Document Projects API #421
- [x] Document Role Skills API #422 _in progress_
- [x] Document Roles API #423 _in progress_
- [x] Document Skills API #424 _in progress_
- [x] Document Slugged Routes API #425
- [x] Document Tokens API #426
- [x] Document User Categories API #427
- [x] Document User Roles API #428
- [x] Document User Skills API #429
- [x] Document Users API #430

**Comment by green-arrow** [comment]
@JoshSmith a couple general questions for these API docs:
- It looks like the "OAuth Grant Request" object is being put as an attribute for every single request. Is this correct? It seems like that is only used on the initial OAuth token request, and the bearer token used in the header for all other API calls.
- The docs reference `Authorization: Basic...`, but I think should be `Bearer`, is there some reason that `Basic` is used instead?

**Comment by joshsmith** [comment]
`Bearer` and not `Basic` yeah. Needs fixed. We can open a separate issue for that.

**Comment by joshsmith** [comment]
It's possible your first point is also a mistake. I would also open a separate issue there. It seems incorrect, but won't be able to verify for a bit. Do any others see incongruence there?

**Comment by christopherstyles** [comment]
I’ve been meaning to update the [`Basic` -> `Bearer`] issue in a separate PR. @JoshSmith if you create an issue for it, go ahead and assign it to me?
